In [1]:
import numpy as np

In [3]:
a1 = np.random.randint(0,19,size=(4,5))
a1

array([[ 4,  0,  1,  0, 10],
       [ 7, 17, 15, 18, 12],
       [ 9,  6,  5,  4,  6],
       [ 0,  6,  9,  8, 18]])

In [5]:
#返回一个新的数组，不改变原有数组
a1.reshape((5,4))

array([[ 4,  0,  1,  0],
       [10,  7, 17, 15],
       [18, 12,  9,  6],
       [ 5,  4,  6,  0],
       [ 6,  9,  8, 18]])

In [7]:
a1

array([[ 4,  0,  1,  0, 10],
       [ 7, 17, 15, 18, 12],
       [ 9,  6,  5,  4,  6],
       [ 0,  6,  9,  8, 18]])

In [9]:
#直接对原有数组做更改
a1.resize((5,4))
a1

array([[ 4,  0,  1,  0],
       [10,  7, 17, 15],
       [18, 12,  9,  6],
       [ 5,  4,  6,  0],
       [ 6,  9,  8, 18]])

In [18]:
#flatten是将数组扁平化，然后返回拷贝
a2 = a1.flatten()
a2[0]=100
print(a1[0,0])

4


In [20]:
#功能同flatten，但返回的是一个引用
a3 = a1.ravel()
a3[0] = 100
print(a1[0,0])

100


#不同数组想要组合，可以利用一下函数来实现
#vstack(垂直叠加) hstack(水平叠加) concatenate(a,b,axis) 0为垂直，1为水平，None为合成一个一维数组(先进行叠加，再转换成一维数组)

In [25]:
b1 = np.random.randint(0,10,size=(3,4))
b2 = np.random.randint(0,10,size=(2,4))
print("我是b1\n",b1)
print("我是b2\n",b2)

我是b1
 [[1 6 6 5]
 [5 0 6 6]
 [7 1 7 7]]
我是b2
 [[1 7 7 2]
 [0 3 8 5]]


In [34]:
b3 = np.vstack([b1,b2])
b3

array([[1, 6, 6, 5],
       [5, 0, 6, 6],
       [7, 1, 7, 7],
       [1, 7, 7, 2],
       [0, 3, 8, 5]])

#垂直切割hsplit,水平切割vsplit，如果控制切割位置，第二个参数设置为元组

In [32]:
c1 = np.random.randint(0,19,size=(4,5))
print(c1)
np.hsplit(c1,5)

[[ 1  4  6  4 11]
 [ 8 12  2  2 14]
 [ 0  6  6  8  5]
 [14  4  6  4  1]]


[array([[ 1],
        [ 8],
        [ 0],
        [14]]),
 array([[ 4],
        [12],
        [ 6],
        [ 4]]),
 array([[6],
        [2],
        [6],
        [6]]),
 array([[4],
        [2],
        [8],
        [4]]),
 array([[11],
        [14],
        [ 5],
        [ 1]])]

In [35]:
np.hsplit(c1,(1,2))

[array([[ 1],
        [ 8],
        [ 0],
        [14]]),
 array([[ 4],
        [12],
        [ 6],
        [ 4]]),
 array([[ 6,  4, 11],
        [ 2,  2, 14],
        [ 6,  8,  5],
        [ 6,  4,  1]])]

In [41]:
t1 = np.random.randint(0,10,size=(3,4))
print(t1)
print("t1的转置为\n",t1.T)
#transpose返回一个新的数组，引用
print("t1的转置为\n",t1.transpose())

[[0 8 2 2]
 [5 0 0 0]
 [3 5 5 3]]
t1的转置为
 [[0 5 3]
 [8 0 5]
 [2 0 5]
 [2 0 3]]
t1的转置为
 [[0 5 3]
 [8 0 5]
 [2 0 5]
 [2 0 3]]
