In [2]:
import numpy as np

In [4]:
#不进行拷贝，只是简单的赋值
a = np.arange(12)
b = a
print(b is a)

True


In [6]:
#Shallow Copy，只拷贝栈区空间，但并不改变指向的堆区空间
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
c = a.view()
print(c is a)

False


In [10]:
c[0] = 100
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11]


In [12]:
#Deep Copy,对栈区以及堆区各自拷贝
d = a.copy()
print(d is a)

False


In [13]:
d[1] = 200
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11]
