In [1]:
import numpy as np

In [2]:
scores = np.random.randint(0,100,size=(20,2))
scores

array([[62, 77],
       [44, 76],
       [49, 54],
       [ 2, 17],
       [22, 11],
       [68, 32],
       [ 8, 84],
       [96, 32],
       [58, 91],
       [37, 91],
       [67, 93],
       [30, 27],
       [37, 42],
       [21, 62],
       [38, 64],
       [70, 23],
       [85, 62],
       [91, 78],
       [80, 53],
       [77, 88]])

In [3]:
#delimiter为分割符，header中分割需要与该参数一致，comments为表头符号，默认为"#"
#csv只能保存一维和二维数组
np.savetxt("score.csv",scores,delimiter=",",header="English,Math",comments="",fmt="%d")
#help(np.savetxt)

In [4]:
b = np.loadtxt("score.csv",dtype=np.int,delimiter=",",skiprows=1)
print(b)
#help(np.loadtxt)

[[62 77]
 [44 76]
 [49 54]
 [ 2 17]
 [22 11]
 [68 32]
 [ 8 84]
 [96 32]
 [58 91]
 [37 91]
 [67 93]
 [30 27]
 [37 42]
 [21 62]
 [38 64]
 [70 23]
 [85 62]
 [91 78]
 [80 53]
 [77 88]]


In [5]:
#numpy特有存储方式，save和load，save对应文件格式.npy，savez对应文件格式.npz，可以存储多维数组
#存储非文本类型文件，不可设置header
c = np.random.randint(0,10,size=(2,3))
print(c)
np.save("c",c)

[[1 7 1]
 [0 1 6]]


In [6]:
np.load("c.npy")

array([[1, 7, 1],
       [0, 1, 6]])