In [1]:
import numpy as np

In [2]:
c = np.random.randint(0,100,size=(3,20))
c

array([[ 6, 28, 67, 35, 50, 87, 83,  6, 77, 84, 75, 11, 41, 41, 16, 86,
        22, 47, 35, 75],
       [18, 33,  5, 75, 12,  5, 85, 92, 45, 86,  7, 44, 10, 32, 21, 56,
        81, 43, 67, 36],
       [38, 91,  5, 37, 76, 37, 11, 66, 10, 82, 16, 35, 35, 29, 14, 92,
        35, 84, 64, 73]])

In [4]:
np.apply_along_axis(lambda x: x[np.logical_and(x!=x.max(),x!=x.min())].mean(), axis=1, arr=c)

array([51.35294118, 44.17647059, 46.27777778])

In [8]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
d = np.random.randint(0,10,size=(3,5))
d

array([[2, 1, 8, 1, 8],
       [6, 4, 5, 0, 0],
       [6, 1, 0, 4, 1]])

In [12]:
np.unique(d)

array([0, 1, 2, 4, 5, 6, 8])

In [13]:
np.unique(d,return_counts=True)

(array([0, 1, 2, 4, 5, 6, 8]), array([3, 4, 1, 2, 1, 2, 2], dtype=int64))