In [2]:
import numpy as np

In [7]:
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [9]:
b = np.array([1,2,3,4,5], dtype=np.int8)
print(b)
print(b.dtype)

[1 2 3 4 5]
int8


In [11]:
c = np.array([1,2,3,4,5], dtype=np.float16)
print(c)
print(c.dtype)

[1. 2. 3. 4. 5.]
float16


In [16]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
d = np.array([Person('小张',18), Person('小王',18)])
print(d)
print(d.dtype)

object


In [21]:
f = np.array(["a","aa"],dtype='S')
print(f)
print(f.dtype)
uf = f.astype('U')
print(uf)
print(uf.dtype)
print(f)

[b'a' b'aa']
|S2
['a' 'aa']
<U2
[b'a' b'aa']


*numpy本身基于C语言编写，保留了C语言复杂多样的数据类型特点
*numpy考虑处理海量数据的性能，为节省内存空间，因而有了多种数据类型