In [1]:
import numpy as np

In [2]:
a = [1, 2.3, '4']
a

[1, 2.3, '4']

In [6]:
c=np.array([1, 2.3, '4'])
c

array(['1', '2.3', '4'], dtype='<U32')

In [10]:
#创建数组
#1. np.array()
b = np.array([1,2,3])
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [15]:
#2 np.arange()
b = np.arange(10)
c = np.arange(0,10,2)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [22]:
#3. np.random.random()创建n行m列数组
b = np.random.random((2,2))
b
#创建整形范围在0到10之间大小为3×3的数组
c = np.random.randint(0, 10, size=(3, 3))
c

array([[5, 2, 1],
       [1, 9, 3],
       [9, 3, 7]])

In [30]:
c = np.zeros((3, 3))
print(c)
d = np.full((3,3),9)
print(d)
e = np.ones((3,2))
print(e)
f = np.eye(3)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[9 9 9]
 [9 9 9]
 [9 9 9]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
