In [2]:
import numpy as np

In [5]:
a = np.random.uniform(-10,10,size=(3,5))
a

array([[-8.38011857,  3.88575655,  2.32669914,  0.83892183,  8.47151557],
       [-4.68871042, -2.30297464,  9.3831956 ,  0.75656038,  1.92893979],
       [ 8.81247987, -9.63303307, -9.73641836, -7.89702835,  5.24709273]])

In [7]:
np.sqrt(a)

<ipython-input-7-c2e2b10f3bad>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([[       nan, 1.97123224, 1.52535214, 0.91592676, 2.91058681],
       [       nan,        nan, 3.06320022, 0.86980479, 1.38886277],
       [2.96858213,        nan,        nan,        nan, 2.29065334]])

In [10]:
np.square(a)

array([[70.22638729, 15.09910399,  5.41352888,  0.70378983, 71.76657611],
       [21.9840054 ,  5.30369217, 88.04435973,  0.57238361,  3.72080872],
       [77.65980143, 92.79532615, 94.79784244, 62.36305676, 27.53198214]])

In [11]:
np.sign(a)

array([[-1.,  1.,  1.,  1.,  1.],
       [-1., -1.,  1.,  1.,  1.],
       [ 1., -1., -1., -1.,  1.]])