In [2]:
import numpy as np

In [29]:
np.random.seed(1)
print(np.random.rand())
# help(np.random.seed)
print(np.random.rand())

0.417022004702574
0.7203244934421581


In [31]:
np.random.randn(2,3)
#生成服从标准正态分布的随机数

array([[ 0.3190391 , -0.24937038,  1.46210794],
       [-2.06014071, -0.3224172 , -0.38405435]])

In [33]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.random.choice(data,5)

array([1, 0, 1, 8, 8])

In [37]:
data1 = np.arange(10)
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.random.shuffle(data1)
data1

array([7, 6, 3, 4, 5, 9, 0, 2, 8, 1])

In [49]:
x = np.array([[0,1],[2,3]])
x.sum(axis=0)

array([2, 4])

In [51]:
y = np.arange(12).reshape(2,6)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [53]:
y.max(axis=0)

array([ 6,  7,  8,  9, 10, 11])

In [54]:
y.max(axis=1)

array([ 5, 11])